version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install flake8
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install flake8
      - run:
          name: Lint code
          command: |
            . venv/bin/activate
            flake8 app.py tests/
      - run:
          name: Lint code
          command: |
            . venv/bin/activate
            flake8 .

  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install pytest
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest tests/

  coverage:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install coverage
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install coverage pytest
      - run:
          name: Run coverage
          command: |
            . venv/bin/activate
            coverage run -m pytest
            coverage report --fail-under=80

  security:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install bandit
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install bandit
      - run:
          name: Run Bandit security scan
          command: |
            . venv/bin/activate
            bandit -r app.py

workflows:
  flask_hit_counter_pipeline:
    jobs:
      - lint
      - test
      - coverage
      - security
